CrpMon.Portal/Controllers/SeguridadController.cs
using System;
using System.Net;
using System.Configuration;
using System.Web.Mvc;
using System.Threading.Tasks;
using System.Collections.Generic;
using CrpMon.Comunes.Modelos.Objetos;
using CrpMon.Comunes.Modelos.Vistas;
using CrpMon.ServiciosWeb;
using RestSharp;
using Newtonsoft.Json.Linq;

namespace CrpMon.Portal.Controllers
{
    [Idioma]
    public class SeguridadController : Controller
    {
        RestfulApi api = new RestfulApi(ConfigurationManager.AppSettings["APIURL"].ToString(),
                                        Convert.ToInt32(ConfigurationManager.AppSettings["GeneralTimeout"].ToString()));

        [ValidaSesion]
        public ActionResult IniciarSesion()
        {
            return View();
        }

        [ValidaUsuario]
        public ActionResult CerrarSesion()
        {
            Session.Clear();
            TempData.Clear();

            return RedirectToAction("Index", "Home");
        }

        [ValidaSesion]
        public ActionResult Registro()
        {
            return View();
        }

        [ValidaUsuario]
        public ActionResult PrimerCompra()
        {
            return View();
        }

        [ValidaUsuario]
        public ActionResult Confirmar()
        {
            return View();
        }

        [HttpPost]
        public JsonResult Autenticar(CInicioSesion modelo)
        {
            CPersona resultado = new CPersona();

            try
            {
                IRestResponse WSR = Task.Run(() => api.Post("Seguridad/Autenticar", modelo)).Result;
                if (WSR.StatusCode == HttpStatusCode.OK)
                {
                    bool bResult;
                    try
                    {
                        resultado = JObject.Parse(WSR.Content).ToObject<CPersona>();
                        Session["USUARIO"] = resultado;
                        Session["LOGIN"] = modelo;
                        bResult = true;
                    }
                    catch (Exception ex)
                    {
                        bResult = false;
                    }

                    return new JsonResult()
                    {
                        Data = bResult,
                        ContentType = "json",
                        MaxJsonLength = int.MaxValue,
                        JsonRequestBehavior = JsonRequestBehavior.AllowGet
                    };
                }
                else
                {
                    return new JsonResult()
                    {
                        Data = WSR.Content,
                        ContentType = "json",
                        MaxJsonLength = int.MaxValue,
                        JsonRequestBehavior = JsonRequestBehavior.AllowGet
                    };
                }
            }
            catch (Exception ex)
            {
                return new JsonResult()
                {
                    Data = ex.Message,
                    ContentType = "json",
                    MaxJsonLength = int.MaxValue,
                    JsonRequestBehavior = JsonRequestBehavior.AllowGet
                };
            }
        }

        [HttpPost]
        public JsonResult Registrar(CRegistro modelo)
        {
            try
            {
                if (modelo != null)
                {
                    IRestResponse WSR = Task.Run(() => api.Put("Seguridad/Registrar", modelo)).Result;
                    if (WSR.StatusCode == HttpStatusCode.OK)
                    {
                        bool result = false;
                        bool.TryParse(WSR.Content, out result);
                            
                        Autenticar(new CInicioSesion() { vNombreUsuario = modelo.vNombreUsuario, vContrasena = modelo.vContrasena });

                        return new JsonResult()
                        {
                            Data = result,
                            ContentType = "json",
                            MaxJsonLength = int.MaxValue,
                            JsonRequestBehavior = JsonRequestBehavior.AllowGet
                        };
                    }
                    else
                    {
                        return new JsonResult()
                        {
                            Data = WSR.Content,
                            ContentType = "json",
                            MaxJsonLength = int.MaxValue,
                            JsonRequestBehavior = JsonRequestBehavior.AllowGet
                        };
                    }
                }
                else
                {
                    return new JsonResult()
                    {
                        Data = "El modelo viene nulo",
                        ContentType = "json",
                        MaxJsonLength = int.MaxValue,
                        JsonRequestBehavior = JsonRequestBehavior.AllowGet
                    };
                }
            }
            catch (Exception ex)
            {
                return new JsonResult()
                {
                    Data = ex.Message,
                    ContentType = "json",
                    MaxJsonLength = int.MaxValue,
                    JsonRequestBehavior = JsonRequestBehavior.AllowGet
                };
            }
        }

        [HttpPost]
        public JsonResult Comprar(CProducto modelo)
        {
            try
            {
                if (modelo != null)
                {
                    CCompra compra = new CCompra() {
                        persona = (CPersona)Session["USUARIO"],
                        producto = modelo
                    };

                    IRestResponse WSR = Task.Run(() => api.Put("Registro/Compra", compra)).Result;
                    if (WSR.StatusCode == HttpStatusCode.OK)
                    {
                        bool result = false;
                        bool.TryParse(WSR.Content, out result);

                        Autenticar((CInicioSesion)Session["LOGIN"]);

                        if (result == true)
                        {
                            return new JsonResult()
                            {
                                Data = true,
                                ContentType = "json",
                                MaxJsonLength = int.MaxValue,
                                JsonRequestBehavior = JsonRequestBehavior.AllowGet
                            };
                        }
                        else
                        {
                            return new JsonResult()
                            {
                                Data = WSR.Content,
                                ContentType = "json",
                                MaxJsonLength = int.MaxValue,
                                JsonRequestBehavior = JsonRequestBehavior.AllowGet
                            };
                        }
                    }
                    else
                    {
                        return new JsonResult()
                        {
                            Data = WSR.Content,
                            ContentType = "json",
                            MaxJsonLength = int.MaxValue,
                            JsonRequestBehavior = JsonRequestBehavior.AllowGet
                        };
                    }
                }
                else
                {
                    return new JsonResult()
                    {
                        Data = "El modelo viene nulo",
                        ContentType = "json",
                        MaxJsonLength = int.MaxValue,
                        JsonRequestBehavior = JsonRequestBehavior.AllowGet
                    };
                }
            }
            catch (Exception ex)
            {
                return new JsonResult()
                {
                    Data = ex.Message,
                    ContentType = "json",
                    MaxJsonLength = int.MaxValue,
                    JsonRequestBehavior = JsonRequestBehavior.AllowGet
                };
            }
        }

        [ValidaUsuario]
        [HttpPost]
        public JsonResult Menu()
        {
            List<CMenu> data = new List<CMenu>();

            IRestResponse WSR = Task.Run(() => api.Get("Seguridad/Menu", "Idioma=" + Convert.ToInt32(Session["IDIOMA"].ToString()))).Result;
            if (WSR.StatusCode == HttpStatusCode.OK)
            {
                string urlbase = Url.Content("~/CrpMonPortal/Imagenes/Menu/");
                data = JArray.Parse(WSR.Content).ToObject<List<CMenu>>();

                data.ForEach(x => {
                    x.imageUrl = urlbase + x.imageUrl;
                    x.url = Url.Action(x.Accion, x.Controlador);
                });
            }
            
            return new JsonResult()
            {
                Data = data,
                ContentType = "json",
                MaxJsonLength = Int32.MaxValue,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }

        [ValidaUsuario]
        [HttpPost]
        public JsonResult ValidarTran()
        {
            CInicioSesion login = (CInicioSesion)Session["LOGIN"];
            CTransaccion transaccion = (CTransaccion)Session["TRANSACCION"];

            IRestResponse WSR = Task.Run(() => api.Get("Operaciones/Verifica_EstadoTransaccion", "pUsuario=" + login.vNombreUsuario + "&pID_Transaccion_Monedero=" + transaccion.Transaccion_Monedero)).Result;
            if (WSR.StatusCode == HttpStatusCode.OK)
            {
                if (WSR.Content.ToString().Replace("\"","") == "Complete")
                {
                    Session.Clear();
                    TempData.Clear();


CrpMon.Portal/Views/Seguridad/Confirmar.cshtml
@using CrpMon.Comunes.Modelos.Vistas
@using CrpMon.Comunes.Modelos.Objetos

@{
    CPersona persona = (CPersona)Session["USUARIO"];
    CTransaccion transaccion = (CTransaccion)Session["TRANSACCION"];
    string nombre = persona.Nombres + " " + persona.Apellidos;
    
    Layout = "~/Views/Shared/_LoginLayout.cshtml";
}

<script src="@Url.Content("~/CrpMonPortal/Angular/Apps/LoginApp.js")"></script>
<script src="@Url.Content("~/CrpMonPortal/Angular/Controllers/ConfirmarCtrl.js")"></script>

<div class="login-box confirmar" ng-controller="ConfirmarCtrl">
    <div class="logo-enterprise">
        <img src="~/CrpMonPortal/Imagenes/logo.png" />
    </div>
    <div class="form-registro">
        <div class="legend">{{ModeloVista.lblTitulo}}</div>
        <div class="legend">{{ModeloVista.lblSubtitulo}}</div>
        <div class="qr-viewer">
            <img ng-src="{{Data.Monedero_Qrcode_Url}}" border="0" style="display: block;">
        </div>
        <div class="legend" style="text-align:left;"><strong>{{ModeloVista.lblTotal}} </strong> {{Data.Monedero_Amount}} (ETH)</div>
        <div class="legend" style="text-align:left;"><strong>{{ModeloVista.lblTiempo}} </strong> {{Data.TiempoAproximado}}</div>
        <div class="legend" style="text-align:left;"><strong>{{ModeloVista.lblDireccion}} </strong> {{Data.Monedero_Address}}</div>
        <div class="error">{{msgError}}</div>
    </div>
</div>

CrpMon.Portal/Views/Seguridad/IniciarSesion.cshtml
@{
    Layout = "~/Views/Shared/_LoginLayout.cshtml";
}

<script src="@Url.Content("~/CrpMonPortal/Angular/Generales/Funciones.js")"></script>
<script src="@Url.Content("~/CrpMonPortal/Angular/Apps/LoginApp.js")"></script>
<script src="@Url.Content("~/CrpMonPortal/Angular/Controllers/LoginCtrl.js")"></script>

<div class="login-box" ng-controller="LoginCtrl">
    <div class="language-container">
        <div class="col-4 float-right">
            <select name="kddIdioma" kendo-drop-down-list="kddIdioma"
                    k-data-source="kddIdiomaDS"
                    k-options="kddIdiomaOPC"
                    style="width: 100%"></select>
        </div>
    </div>
    <div class="logo-enterprise">
        <img src="~/CrpMonPortal/Imagenes/logo.png" />
    </div>
    <div class="form-login">
        <form name="frmLogin" novalidate autocomplete="off">
            <div class="col-12">
                <input ng-model="ModeloLogin.vNombreUsuario" type="text" class="k-textbox UsuarioInput" id="txtUsuario" name="txtUsuario" style="width:100%;" placeholder="{{ModeloVista.lblUsuario}}" required />
                <div class="error">
                    <span ng-show="frmLogin.txtUsuario.$error.required">*</span>
                </div>
            </div>
            <div class="col-12">
                <input ng-model="ModeloLogin.vContrasena" type="password" class="k-textbox PassInput" id="txtContrasena" name="txtContrasena" style="width:100%;" placeholder="{{ModeloVista.lblPassword}}" required />
                <div class="error">
                    <span ng-show="frmLogin.txtContrasena.$error.required">*</span>
                </div>
            </div>
            <div class="col-12">
                <div class="error" data-ng-bind="AutenticarError"></div>
            </div>
            <div class="col-12 button-container">
                <button id="btnLogin" type="submit" class="k-button k-primary" ng-disabled="frmLogin.$invalid" ng-click="Ingresar()">
                    <img src="~/CrpMonPortal/Imagenes/Vistas/InicioSesion.png" />
                    <span>{{ModeloVista.btnLogin}}</span>
                </button>
                <button id="btnRefresh" type="reset" class="k-button">
                    <span>{{ModeloVista.btnCancelar}}</span>
                </button>
            </div>
            <div class="col-12">
                <span class="alert">{{ModeloVista.lblNoRegistro}} <a href="javascript:Registrar();">{{ModeloVista.linkRegistro}}</a></span>
                <span class="alert">{{ModeloVista.lblOlvidaPass}} <a href="javascript:alert('Funcionalidad en construcción.');">{{ModeloVista.linkRecuperar}}</a></span>
            </div>
        </form>
    </div>
</div>

<script>
    function Registrar() {
        $('.blocker').show();
        window.location.href = '@Url.Action("Registro", "Seguridad")';
    }
</script>

CrpMon.Portal/Views/Seguridad/PrimerCompra.cshtml
@{
    Layout = "~/Views/Shared/_LoginLayout.cshtml";
}

<script src="@Url.Content("~/CrpMonPortal/Angular/Apps/LoginApp.js")"></script>
<script src="@Url.Content("~/CrpMonPortal/Angular/Controllers/PrimerCompraCtrl.js")"></script>

<div class="login-box compra" ng-app="LoginApp" ng-controller="PrimerCompraCtrl">
    <div class="logo-enterprise">
        <img src="~/CrpMonPortal/Imagenes/logo.png" />
    </div>
    <div class="form-registro">
        <div class="legend">{{ModeloVista.lblPrincipal}}</div>
        <div kendo-list-view="klvProducto" id="klvProducto" k-data-source="source" k-options="klvProductoOpt">
            <div class="contenedor-producto" k-template ng-click="CargarProducto(dataItem)">
                <div class="celda">
                    <img ng-src="{{dataItem.Img_Url}}" />
                </div>
                <div class="celda informacion">
                    <div class="item nombre">{{ dataItem.Descripcion }}</div>
                    <div class="item">{{ dataItem.Mensaje_Monto }}</div>
                    <div class="item">{{ dataItem.Mensaje_Binario }}</div>
                    <div class="item">{{ dataItem.Mensaje_Alerta }}</div>
                    <div class="item">{{ dataItem.Mensaje_Dia }}</div>
                    <div class="item ultimo">{{ dataItem.Mensaje_OutMax }}</div>
                </div>
            </div>
        </div>
        <div class="col-12">
            <div class="error" data-ng-bind="MensajeError"></div>
        </div>
        <div class="col-12 button-container">
            <button id="btnLogin" type="submit" class="k-button k-primary" ng-click="Comprar()">
                <span>{{ModeloVista.btnComprar}}</span>
            </button>
            <button type="button" class="k-button" ng-click="Cancelar()">
                <span>{{ModeloVista.btnCancelar}}</span>
            </button>
        </div>
    </div>
</div>

CrpMon.Portal/Views/Seguridad/Registro.cshtml
@{
    Layout = "~/Views/Shared/_LoginLayout.cshtml";
    string patrocinador = (TempData["PATROCINADOR"] == null) ? null : TempData["PATROCINADOR"].ToString();
}

<script src="@Url.Content("~/CrpMonPortal/Angular/Generales/Funciones.js")"></script>
<script src="@Url.Content("~/CrpMonPortal/Angular/Apps/LoginApp.js")"></script>
<script src="@Url.Content("~/CrpMonPortal/Angular/Controllers/RegistroCtrl.js")"></script>

<div class="login-box" ng-controller="RegistroCtrl">
    <div class="language-container">
        <div class="col-4 float-right">
            <select name="kddIdioma" kendo-drop-down-list="kddIdioma"
                    k-data-source="kddIdiomaDS"
                    k-options="kddIdiomaOPC"
                    style="width: 100%"></select>
        </div>
    </div>
    <div class="logo-enterprise">
        <img src="~/CrpMonPortal/Imagenes/logo.png" />
    </div>
    <div class="form-registro">
        <form name="frmRegistro" novalidate autocomplete="off">
            <div class="col-6">
                @if (string.IsNullOrEmpty(patrocinador) || string.IsNullOrWhiteSpace(patrocinador))
                {
                    <input ng-model="ModeloRegistro.vPatrocinador" type="text" class="k-textbox PatrocinadorInput" id="txtPatrocinador" name="txtPatrocinador" style="width:100%;"
                           placeholder="{{ModeloVista.lblPatrocinador}}" title="Patrocinador" required minlength="3" />
                }
                else
                {
                    <input ng-model="ModeloRegistro.vPatrocinador" type="text" class="k-textbox PatrocinadorInput" id="txtPatrocinador" name="txtPatrocinador" style="width:100%;"
                           placeholder="{{ModeloVista.lblPatrocinador}}" title="Patrocinador" required minlength="3" readonly />
                }
                <div class="error">
                    <span ng-show="frmRegistro.txtPatrocinador.$error.required">*</span>
                    <span ng-show="frmRegistro.txtPatrocinador.$error.minlength">{{ModeloVista.vldPatrocinadorMinLength}}</span>
                </div>
            </div>
            <div class="col-6">
                <input ng-model="ModeloRegistro.vNombreUsuario" type="text" class="k-textbox UsuarioInput" id="txtUsuario" name="txtUsuario" style="width:100%;" 
                       placeholder="{{ModeloVista.lblUsuario}}" title="Usuario" required exclude-to="frmRegistro.txtPatrocinador" minlength="3" />
                <div class="error">
                    <span ng-show="frmRegistro.txtUsuario.$error.required">*</span>
                    <span ng-show="frmRegistro.txtUsuario.$error.excludeTo">{{ModeloVista.vldUsuarioMinExcludeTo}}</span>
                    <span ng-show="frmRegistro.txtUsuario.$error.minlength">{{ModeloVista.vldUsuarioMinLength}}</span>
                </div>
            </div>
            <div class="col-6">
                <input ng-model="ModeloRegistro.vNombres" type="text" class="k-textbox NombresInput" id="txtNombres" name="txtNombres" style="width:100%;" 
                       placeholder="{{ModeloVista.lblNombres}}" title="Nombres" required minlength="2" />
                <div class="error">
                    <span ng-show="frmRegistro.txtNombres.$error.required">*</span>
                    <span ng-show="frmRegistro.txtNombres.$error.minlength">{{ModeloVista.vldNombresMinLength}}</span>
                </div>
            </div>
            <div class="col-6">
                <input ng-model="ModeloRegistro.vApellidos" type="text" class="k-textbox ApellidosInput" id="txtApellidos" name="txtApellidos" style="width:100%;" 
                       placeholder="{{ModeloVista.lblApellidos}}" title="Apellidos" required minlength="2" />
                <div class="error">
                    <span ng-show="frmRegistro.txtApellidos.$error.required">*</span>
                    <span ng-show="frmRegistro.txtApellidos.$error.minlength">{{ModeloVista.vldApellidosMinLength}}</span>
                </div>
            </div>
            <div class="col-12">
                <input ng-model="ModeloRegistro.vCorreoElectronico" type="email" class="k-textbox EmailInput" id="txtEmail" name="txtEmail" style="width:100%;" 
                       placeholder="{{ModeloVista.lblEmail}}" title="Correo electrónico" required />
                <div class="error">
                    <span ng-show="frmRegistro.txtEmail.$error.required">*</span>
                    <span ng-show="frmRegistro.txtEmail.$error.email">{{ModeloVista.vldEmailFormat}}</span>
                </div>
            </div>
            <div class="col-12">
                <input ng-model="ModeloRegistro.vCarteraCryptoMoneda" type="text" class="k-textbox BilleteraInput" id="txtCartera" name="txtCartera" style="width:100%;" 
                       placeholder="{{ModeloVista.lblCartera}}" title="Cartera Criptomoneda" required />
                <div class="error">
                    <span ng-show="frmRegistro.txtCartera.$error.required">*</span>
                </div>
            </div>
            <div class="col-6">
                <input ng-model="ModeloRegistro.vContrasena" type="password" class="k-textbox PassInput" id="txtContrasena" name="txtContrasena" style="width:100%;" 
                       placeholder="{{ModeloVista.lblPassword}}" title="Contraseña" required minlength="8" />
                <div class="error">
                    <span ng-show="frmRegistro.txtContrasena.$error.required">*</span>
                    <span ng-show="frmRegistro.txtContrasena.$error.minlength">{{ModeloVista.vldPasswordMinLength}}</span>
                </div>
            </div>
            <div class="col-6">
                <input ng-model="ModeloRegistro.vConfirmaContrasena" type="password" class="k-textbox PassInput" id="txtConfirma" name="txtConfirma" style="width:100%;" 
                       placeholder="{{ModeloVista.lblConfirmar}}" title="Confirmar" required compare-to="frmRegistro.txtContrasena" minlength="8" />
                <div class="error">
                    <span ng-show="frmRegistro.txtConfirma.$error.required">*</span>
                    <span ng-show="frmRegistro.txtConfirma.$error.compareTo">{{ModeloVista.vldConfirmarExcludeTo}}</span>
                    <span ng-show="frmRegistro.txtConfirma.$error.minlength">{{ModeloVista.vldConfirmarMinLength}}</span>
                </div>
            </div>
            <div class="col-12">
                <div class="error" data-ng-bind="RegistroError"></div>
            </div>
            <div class="col-12 button-container">
                <button id="btnLogin" type="submit" class="k-button k-primary" ng-disabled="frmRegistro.$invalid" ng-click="Registrar()" >
                    <img src="~/CrpMonPortal/Imagenes/Vistas/InicioSesion.png" />
                    <span>{{ModeloVista.btnRegistrar}}</span>
                </button>
                <button type="button" class="k-button" onclick="javascript:Cancelar();" >
                    <span>{{ModeloVista.btnCancelar}}</span>
                </button>
            </div>
        </form>
    </div>
</div>

<script>
    var PatrocinadorAsignador = '@patrocinador';

    function Cancelar() {
        $('.blocker').show();
        window.location.href = '@Url.Action("IniciarSesion","Seguridad")';
    }
</script>